const AUTH0_DOMAIN: string = process.env.AUTH0_DOMAIN;
const AUTH0_CLIENT_ID: string = process.env.AUTH0_CLIENT_ID;
const AUTH0_CLIENT_SECRET: string = process.env.AUTH0_CLIENT_SECRET;
const AUTH0_USERNAME: string = process.env.AUTH0_USERNAME;
const AUTH0_PASSWORD: string = process.env.AUTH0_PASSWORD;

export { AUTH0_DOMAIN, AUTH0_CLIENT_ID, AUTH0_CLIENT_SECRET, AUTH0_USERNAME, AUTH0_PASSWORD };
